# 문자열 연결 연산자 : +
print()
print("# 문자열 연결 연산자 : +")
print("안녕" + "하세요")
print("안녕하세요" + "!")
print()
# 문자열 반복 연산자 : *
print("# 문자열 반복 연산자 : *")
print("Hi"*3)
print(3*"Hi")
print()
# 문자 선택 연산자(인덱싱) : []
print("# 문자 선택 연산자(인덱싱) : []")
print("안녕하세요"[0])
print("안녕하세요"[1])
print("안녕하세요"[2])
print("안녕하세요"[3])
print("안녕하세요"[4])
print()
# 문자열 범위 선택 연산자(슬라이싱) : [:]
print("# 문자열 범위 선택 연산자(슬라이싱) : [:]")
print("안녕하세요")
print("1, 4")
print("안녕하세요"[1:4])
print("0, 2")
print("안녕하세요"[0:2])
print("1, 3")
print("안녕하세요"[1:3])
print("2, 4")
print("안녕하세요"[2:4])
print()
print("1, ")
print("안녕하세요"[1:])
print(", 3")
print("안녕하세요"[:3])
print()